### ISSUE TITLE
[BUG] Particles?

### ISSUE THREAD

**Issue by Axisiser** [mariumbacchus/Soulslike-Weaponry#202] opened 2024-11-05 00:50 UTC
[hs_err_pid8840.log](https://github.com/user-attachments/files/17625412/hs_err_pid8840.log)

**Comment by mariumbacchus** [comment] 2024-11-06 19:59
Refer to [this issue](https://github.com/mariumbacchus/Soulslike-Weaponry/issues/162), the crash is essentially caused by an outdated version of java. Will close this since it is a duplicate.

**Closed as completed by mariumbacchus** 2024-11-06 19:59 UTC
Labels: bug
