### ISSUE TITLE
Crash on 1.19.4

### ISSUE THREAD

**Issue by NantaArthur123** [mariumbacchus/Soulslike-Weaponry#30] opened 2023-05-15 10:08 UTC
I don't know what happened, sorry cannot help much, the thing is I just hop into server and after 3 minutes my mc crashed.

crash log:
[crash-2023-05-15_17.05.32-client.txt](https://github.com/mariumbacchus/Soulslike-Weaponry/files/11476659/crash-2023-05-15_17.05.32-client.txt)

**Comment by mariumbacchus** [comment] 2023-05-18 17:58
It is caused by a conflict between the Iceberg mod and SW. Will be fixed.

**Closed** 2023-05-20 16:37 UTC
