### ISSUE TITLE
Fresh Animations pack causes armor clipping

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#115] opened 2024-04-18 07:02 UTC
Mobs from this mod with armor seem to have clipping issues while using fresh animations. Not sure if there's any way to prevent the animations from being applied to mobs from this mod or if this is something that can be fixed?

**Comment by mariumbacchus** [comment] 2024-04-18 10:40
Which ones specifically? Only the biped ones I assume?

**Comment by NolanHewitt** [comment] 2024-04-19 06:33
Yeah, only the bipeds with armor. Namely the Remnant, Dark Sorcerer, and both Forlorn types. Not sure if there's any way to make it so they use the vanilla animations instead of the fresh animations ones, perhaps some kind of override datapack could be made to make them use vanilla ones if it isn't possible to fix the clipping with fresh animations on this mods side.

**Comment by mariumbacchus** [comment] 2024-04-19 12:10
Yeah I am guessing there is a way, I'll look into it.

**Comment by Dralaon** [comment] 2024-09-25 06:37
While Fresh Animations cause clipping issues, something similar happens with Blue's Better Monsters, the resource pack convert Forlorn (and others biped/humans mobs) into zombies, and completely breaks the model.
Copying the vanilla entity and creating a custom entity to make the calls (instead of calling the vanilla entity and modifying it), probably will solve this issue, but idk, I don't have much technical knowledge.

Anyway. I don't use Fresh Animations, neither Blue's Better Monsters, because they break others mods (such Creeper Overhaul), but when I was trying to use it, thats what I observed.

**Comment by mariumbacchus** [comment] 2024-09-30 12:01
Are all biped mobs affected by it? Like Remnants and Dark Sorcerers, or just the Forlorn?
Those mobs don't extend zombies at all, so it's weird how those too get turned into zombies. This is likely an issue on the resource pack's side since there is no reason it should turn all biped entities into zombies by default.

**Comment by Dralaon** [comment] 2024-09-30 13:06
https://github.com/user-attachments/assets/e054bc39-3cfd-476e-9286-6218b64d64de


Very low quality video, but I think it works. And, yes, Remnants, Dark Sorcerers and Forlorn.

**Comment by mariumbacchus** [comment] 2024-10-01 11:18
That's interesting. I know how to fix the armor clipping issue, but them all turning into zombies is another thing. Not sure there is something I can do about that either since Blues isn't open source (or rather I didn't find the source) so I don't really know what causes it.

**Comment by Dralaon** [comment] 2024-10-02 21:11
Fresh Animations also interprets these mobs as zombies, as it is applying zombie animation.

I did some tests to help.
I tested 3 more resource packs, apparently the ones that require ETF and EMF, cause changes to the model, sounds and/or animations, always using zombies as a base.
Better Zombies (by Noviem) is a similar case to Fresh Animations as it also causes the clipping problem, and have some similarities with Blue's Better Monsters (dismembering mechanic). But it is Open Source, here: https://github.com/l-Noviem-l/BTRZ

"Tissou's Zombie Pack" uses only the ETF, and modifies the sounds of these mobs, matching the zombies. It is not Open Source.

"Among Us Zombies", is a meme pack, does not use ETF or EMF, in turn, it does not modify anything, just the vanilla zombies. It is not Open Source.

I hope it is useful.

**Comment by Dralaon** [comment] 2024-10-02 21:44
Using the Debugging Tool from EMF:

Without Fresh Animations (The base model for Remnant is reporting a zombie.jem and/or drowned_outer.jem entity... with a armor entity (idk): 
![image](https://github.com/user-attachments/assets/59455ebd-f333-4f22-a18b-8e01a039c46a)


With Fresh Animations (duplicates the model for some reason, using model 1 "zombie" and model 2 "drowned_outer", i guess this is where the clipping issue occurs):
![image](https://github.com/user-attachments/assets/d083281e-0124-40f9-8b7b-72d15d5d2b8d)


This debugging tool makes my game run at 3 fps, so i will not test others resources packs for sanity reasons.

**Comment by Dralaon** [comment] 2024-10-02 22:30
I found this:
Forlorn:
https://github.com/mariumbacchus/Soulslike-Weaponry/blob/1.20-1.20.1/src/main/java/net/soulsweaponry/client/renderer/entity/mobs/ForlornRenderer.java

Remnant:
https://github.com/mariumbacchus/Soulslike-Weaponry/blob/1.20-1.20.1/src/main/java/net/soulsweaponry/client/renderer/entity/mobs/RemnantRenderer.java

Dark Sorcerer:
https://github.com/mariumbacchus/Soulslike-Weaponry/blob/1.20-1.20.1/src/main/java/net/soulsweaponry/client/renderer/entity/mobs/DarkSorcererRenderer.java

These "EntityModelLayers.ZOMBIE", "EntityModelLayers.ZOMBIE_INNER_ARMOR" and "EntityModelLayers.ZOMBIE_OUTER_ARMOR" in all of them caught my attention. Maybe thats the cause?

Also in RemnantFeatureRenderer.java has a "EntityModelLayers.DROWNED_OUTER" reported by EMF.
https://github.com/mariumbacchus/Soulslike-Weaponry/blob/1.20-1.20.1/src/main/java/net/soulsweaponry/client/renderer/entity/mobs/RemnantFeatureRenderer.java

**Comment by mariumbacchus** [comment] 2024-10-10 18:24
Thanks for the help throughout this, must be those layers making their models being overridden like you mentioned. As for the armor clipping issues, I found the cause a while back when working on epic fight compatibility, the different FeatureRenderers caused it. I've made changes that should be live next update that fixes the armor clipping issues. I'll look into changing the layers to fix the model overriding soon.

**Comment by mariumbacchus** [comment] 2024-10-10 23:05
I've made custom layers so resourcepacks like Blues Better Monsters won't override the Forlorn and others, the downside of this is that Fresh Animations no longer work on them since they previously used the zombie animations. So either I push this forward where Fresh Animations won't work on the mobs unless I find another way to do this, but Blues issues are fixed, or stay neutral and let packs like Blues break, but Fresh Animations will work fine.

**Comment by NolanHewitt** [comment] 2024-10-11 04:56
Fresh Animations is a much more popular pack so I feel like it would be better to use the method that fresh animations works with.

**Comment by Dralaon** [comment] 2024-10-11 07:50
Even though I don't use Blue's, I think the method of making it compatible makes a lot more sense, as it can avoid problems with other mods and resource packs in the future.

Fresh Animations allows you to create addons that make mobs from other mods compatible. I don't know how to create the addon btw, but since it has this possibility, making it natively "compatible" with Fresh Animations doesn't make sense.
Also, Fresh Animations breaks the Dual Wielding animation, Forlorn looks ugly with this.

**Comment by mariumbacchus** [comment] 2024-10-11 14:53
Alright, I will implement the custom layers and try to make a builtin resourcepack that makes the mod compatible with Fresh Animations.

**Comment by mariumbacchus** [comment] 2024-10-11 21:18
I've made a builtin pack and fixed the layer issues. Changes will be live next update, will close this now. Thanks for the help again.

**Closed as completed by mariumbacchus** 2024-10-11 21:18 UTC
Labels: bug, incompatibility
