### ISSUE TITLE
[BUG] Hallowheart torso armor

### ISSUE THREAD

**Issue by NekoMaster5** [mariumbacchus/Soulslike-Weaponry#172] opened 2024-08-22 11:19 UTC
**Minecraft, modloader and mod versions**
Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: 1.1.3

**Describe the bug**
Crash occur when using the ability of Hallowheart torso (not the infused one, i haven't tested it yet). I don't know if it's because there's too much enchant on this or something, but the use of the ability force the game to close by himself with a screen that "save the world"

**Add logs**
The game crashed whilst ticking entity
Error: com.bawnorton.neruina.exception.DoNotHandleException: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "effect" is null

**To Reproduce**
1. Fight any enemy with armor equipped
2. Use the ability
3. See the game close himself

**Expected behavior**
I just wanted the game to not crash and apply wither and all of the other effect on my enemy, like slowness, mining fatigue, burning.

**Other mods or relevant info**
I'm using Prominence 2 modpack

**Comment by NoRestForWicked** [comment] 2024-08-23 02:19
i think it might be a mod incompatibility, I cannot seem to recreate the bug myself :/

**Comment by mariumbacchus** [comment] 2024-08-23 14:56
The crash states it's caused by a library called "com.bawnorton.neruina". This is definitely an incompatibility issue, I suggest making an issue post on their end to solve the issue.

**Comment by NekoMaster5** [comment] 2024-08-23 15:23
oh okok, thank you, i'll go watch it, also, i really enjoy your mod, got the crown today and it's powerful x)

**Comment by mariumbacchus** [comment] 2024-08-24 12:03
Glad to hear it. Will close this since hopefully the other mod devs fixes it. Make another post if this mod is the root cause.

**Closed as completed by mariumbacchus** 2024-08-24 12:03 UTC
Labels: bug
